### ISSUE TITLE
NullPointerException in example class

### ISSUE THREAD

**Issue by BlueMustache** [Doridian/SteamMobileLib#2]
I would love to use this library, but using the default sample class in test, when I login I get a NullPointerException at de.doridian.steammobile.connection.MessageHandler.logon(MessageHandler.java:37).
Please help!
I would love to make something really cool with this.

**Comment by Doridian** [comment]
Sadly steam removed the method for logging in.
It now uses some integrated OAuth via a WebView making it really hard (almost impossible thanks to their CAPTCHA) to do this as a CLI app :(

**Comment by BlueMustache** [comment]
Any workarounds?

**Comment by Doridian** [comment]
Unless someone implements a way that opens a webview to generate a token and then a login through that, no.

**Comment by BlueMustache** [comment]
Isn't there a thing where you can use an audio captcha and the google recognition to hear the code?

**Comment by BlueMustache** [comment]
Would this help? With a Java wrapper?
https://facepunch.com/showthread.php?t=824685&p=17668850&viewfull=1#post17668850

**Comment by Doridian** [comment]
OpenSteamWorks actually hooks into a Steam desktop client and "remote controls" it.
There is also SteamRE or SteamKit2 which basicaly are Steam Desktop Client libraries (they speak the Steam Desktop Protocol which is a UDP based monstrosity).
This speaks the HTTP API only used by the Steam web and mobile clients (which are both able to display a HTML GUI and do so for initial login).
